import { Card } from './types';

export const ALL_CARDS: Card[] = [
  // WORK cards — playing work costs rest (you can't grind without burning out)
  { id: 'work-1', title: 'Deep Work',
    basePoints: 5, tokens: ['work'], costs: ['rest'] },
  { id: 'work-2', title: 'Code Review',
    basePoints: 3, tokens: ['work', 'work'],
    bonus: { required: { type: 'work', count: 2 }, points: 3 } },
  { id: 'work-3', title: 'Strategy Meeting',
    basePoints: 2, tokens: ['work', 'social'],
    bonus: { required: { type: 'social', count: 3 }, points: 4 } },
  { id: 'work-4', title: 'Side Project',
    basePoints: 1, tokens: ['work', 'work', 'work'], costs: ['rest'],
    bonus: { required: { type: 'work', count: 4 }, points: 6 } },
  { id: 'work-5', title: 'Crunch Mode',
    basePoints: 0, tokens: ['work', 'work'], costs: ['rest', 'rest'],
    bonus: { required: { type: 'work', count: 5 }, points: 9 } },

  // FITNESS cards — intense training costs rest
  { id: 'fit-1', title: 'Gym Session',
    basePoints: 5, tokens: ['fitness'], costs: ['rest'] },
  { id: 'fit-2', title: 'Morning Run',
    basePoints: 3, tokens: ['fitness', 'fitness'],
    bonus: { required: { type: 'fitness', count: 2 }, points: 3 } },
  { id: 'fit-3', title: 'Yoga Class',
    basePoints: 2, tokens: ['fitness', 'rest'],
    bonus: { required: { type: 'rest', count: 3 }, points: 4 } },
  { id: 'fit-4', title: 'Cycling Trip',
    basePoints: 1, tokens: ['fitness', 'fitness', 'fitness'],
    bonus: { required: { type: 'fitness', count: 4 }, points: 6 } },
  { id: 'fit-5', title: 'Ultra Training',
    basePoints: 0, tokens: ['fitness', 'fitness'], costs: ['rest'],
    bonus: { required: { type: 'fitness', count: 5 }, points: 9 } },

  // SOCIAL cards — heavy socialising costs work time
  { id: 'soc-1', title: 'Networking Event',
    basePoints: 5, tokens: ['social'], costs: ['work'] },
  { id: 'soc-2', title: 'Friend Dinner',
    basePoints: 3, tokens: ['social', 'social'],
    bonus: { required: { type: 'social', count: 2 }, points: 3 } },
  { id: 'soc-3', title: 'Game Night',
    basePoints: 2, tokens: ['social', 'rest'],
    bonus: { required: { type: 'rest', count: 2 }, points: 4 } },
  { id: 'soc-4', title: 'Team Lunch',
    basePoints: 1, tokens: ['social', 'social', 'social'],
    bonus: { required: { type: 'social', count: 4 }, points: 6 } },
  { id: 'soc-5', title: 'Party Night',
    basePoints: 0, tokens: ['social', 'social'], costs: ['work', 'rest'],
    bonus: { required: { type: 'social', count: 5 }, points: 9 } },

  // REST cards — pure recovery, no costs
  { id: 'rest-1', title: 'Sleep In',
    basePoints: 5, tokens: ['rest', 'rest'] },
  { id: 'rest-2', title: 'Reading Day',
    basePoints: 3, tokens: ['rest'],
    bonus: { required: { type: 'rest', count: 2 }, points: 3 } },
  { id: 'rest-3', title: 'Movie Marathon',
    basePoints: 2, tokens: ['rest', 'social'],
    bonus: { required: { type: 'social', count: 2 }, points: 4 } },
  { id: 'rest-4', title: 'Meditation',
    basePoints: 1, tokens: ['rest', 'rest'],
    bonus: { required: { type: 'rest', count: 4 }, points: 6 } },
  { id: 'rest-5', title: 'Full Rest Day',
    basePoints: 0, tokens: ['rest', 'rest', 'rest'],
    bonus: { required: { type: 'rest', count: 5 }, points: 9 } },

  // BALANCED cards — mix of themes
  { id: 'bal-1', title: 'Productive Morning',
    basePoints: 4, tokens: ['work', 'fitness'], costs: ['rest'],
    bonus: { required: { type: 'work', count: 2 }, points: 2 } },
  { id: 'bal-2', title: 'Social Run',
    basePoints: 3, tokens: ['fitness', 'social'],
    bonus: { required: { type: 'fitness', count: 3 }, points: 3 } },
  { id: 'bal-3', title: 'Work From Cafe',
    basePoints: 3, tokens: ['work', 'social'],
    bonus: { required: { type: 'social', count: 2 }, points: 3 } },
  { id: 'bal-4', title: 'Nature Hike',
    basePoints: 2, tokens: ['rest', 'fitness'],
    bonus: { required: { type: 'fitness', count: 3 }, points: 4 } },
  { id: 'bal-5', title: 'Volunteering',
    basePoints: 1, tokens: ['social', 'work', 'fitness'],
    bonus: { required: { type: 'social', count: 3 }, points: 7 } },
];

